apiVersion: v1 
kind: ConfigMap
metadata:
  name: set-annotations
data:
  foo: bar
  baz: olo
  source: |
    def main():
      fncfg = ctx.resource_list["functionConfig"]["data"]
      for resource in ctx.resource_list["items"]:
        for key in fncfg: 
          resource["metadata"]["annotations"][key] = fncfg[key]
    main()
