apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: set-annotations
params:
  toAdd:
    foo: bar
    baz: olo
source: |
  def main():
    toAdd = ctx.resource_list["functionConfig"]["params"]["toAdd"]
    for resource in ctx.resource_list["items"]:
      for key in toAdd:
        resource["metadata"]["annotations"][key] = toAdd[key]
  main()
